### ISSUE TITLE
May I copy and redistribute from this for my unl0kr package?

### ISSUE THREAD

**Issue by Grosskopf** [ShapeShifter499/osk-sdl_arch#3]
Hi,
I only noticed after copying and playing around and rebuilding for unl0kr, that I might be doing something wrong here. I have an Arch package for unl0kr now that has this package as a foundation and I would love to publish it (under GPL3), but this package has no License file, may I publish that package even though the hook files look an awful lot like the hook files from here? :)

**Comment by root2185** [comment]
@Grosskopf I wanted to use osk-sdl on my device but it opens a black screen.
Can you share unl0kr?

Edit:
Note I use Artix and not Arch.
My device: CHUWI UBook.

**Comment by Grosskopf** [comment]
> @Grosskopf I wanted to use osk-sdl on my device but it opens a black screen. Can you share unl0kr?

I had the same Issue, it is actually documented upstream https://gitlab.com/postmarketOS/osk-sdl/-/issues/148 have you tried touching the blank screen once? on the Shift13mi that I use the accellerometer is not working and so the first event that triggers drawing of the UI is the first touch. On other devices it would be a tilt of the device triggering seemingly instantaniously

I cannot really recommend using unl0kr due to this bug: https://gitlab.com/cherrypicker/unl0kr/-/issues/38 at the moment

I still have one thing I would like to fix and then maybe I'll publish it to github. Not to AUR though, because I don't want to be the person responsible for permanently locking out people that don't have a secondary boot partition in case something goes terribly wrong with unl0kr, which is quite likely since Unl0kr boot partitions are 1Gigabyte big per installed Kernel and tend to permanently break on update if they run out of space, happened twice already for me :) that's why I allways cary a spare boot partition

**Comment by root2185** [comment]
Yes I tried to touch the screen and even to press keys with a physical keyboard. 
I couldn't do anything.

I know that you can launch osk-sdl in a tty, after all it is used in the intramfs.
If I launch it there I get the black screen and I cannot even change tty.
It works on a terminal only.
Therefore I guess that tilting the device won't work.

I can launch unl0kr in a tty and it works fine.
If something goes wrong you can use a usb key with some live system or the installer.

Can you share just to me the unl0kr files meanwhile maybe? Can we talk on matrix?

**Comment by Grosskopf** [comment]
[unl0kr.zip](https://github.com/ShapeShifter499/osk-sdl_arch/files/10787245/unl0kr.zip)
These would be the two files, I noticed they are super similar to the ones in plymouth-encrypt so I will just assume this to be fine, and also in the aur this package has a gpl license so I assume this repo to have the same

**Comment by Grosskopf** [comment]
there is still a known bug with them, when the password has been tried once it should show that but it does not due to one missing line in the hook

**Comment by Grosskopf** [comment]
together with this PKGBUILD you can make it build and you'll be able to cleanly install and remove it
```
pkgname=unl0kr
pkgver=0.3
pkgdesc="unl0kr On-screen Keyboard for FDE"
pkgrel=1
arch=(x86_64)
url="https://gitlab.com/cherrypicker/unl0kr"
license=('GPL3')
depends=(device-mapper cryptsetup mesa)
makedepends=(meson)
_commit="cb7c6f77a961c95e5c71f89c29467a37875742f1"
source=(
    git+https://gitlab.com/cherrypicker/unl0kr.git#commit=${_commit}
    unl0kr-hooks
    unl0kr-install
)
build() {
    cd unl0kr
    git submodule init
    git submodule update
    cd ..
    arch-meson "$pkgname" _build
    meson compile -C _build
}

package() {
    DESTDIR="$pkgdir" meson install --no-rebuild -C _build
    install -Dm644 ${srcdir}/unl0kr-hooks ${pkgdir}/usr/lib/initcpio/hooks/unl0kr
    install -Dm644 ${srcdir}/unl0kr-install ${pkgdir}/usr/lib/initcpio/install/unl0kr
}

md5sums=('SKIP'
         'a33e2ba3e83c76188996c686d0f1640e'
         '79bb712c36c48179ab3eaab9d9d902db')
```

**Comment by root2185** [comment]
Thanks.
It seems that distro are switching to unl0kr, it was made to replace osk-sdl https://gitlab.com/postmarketOS/osk-sdl/-/issues/121 indeed.

**Comment by root2185** [comment]
```
HOOKS=(base udev autodetect modconf block kms filesystems keyboard keymap consolefont lvm2 unl0kr resume fsck)
```
Are those correct? After entering the password it doesn't mount the volumes.
etc/default/grub:
```
GRUB_CMDLINE_LINUX_DEFAULT="quiet cryptdevice=/dev/sda3:system root=/dev/mapper/vg1-system resume=/dev/mapper/vg1-swap"
```
With these hook it works and I can hibernate:
```
HOOKS=(base udev autodetect modconf encrypt kms keyboard keymap consolefont lvm2 resume block filesystems fsck)
```
(I need a keyboard with that).

```
lsblk
NAME             MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINTS
sda                8:0    0 238.5G  0 disk  
├─sda1             8:1    0   285M  0 part  /boot/efi
├─sda2             8:2    0   954M  0 part  /boot
├─sda3             8:3    0   200G  0 part  
│ └─system       254:0    0   200G  0 crypt 
│   ├─vg1-system 254:1    0 191.6G  0 lvm   /
│   └─vg1-swap   254:2    0   8.4G  0 lvm   [SWAP]
```

**Comment by Grosskopf** [comment]
I allways have unl0kr as a replacement for encrypt, for me it is

`HOOKS="base udev autodetect modconf block keyboard keymap consolefont unl0kr plymouth openswap resume filesystems"`

I think filesystems should be really late because I believe it tries to open files, and thus should happen after the files are unencrypted... with lvm2 i'm unsure where that goes, propably before unl0kr, because unl0kr needs to unlock a sub-partition inside an lvm partition...

also I heard somewhere something about cryptdevices being better of with uuid defintion..
propably that was this: https://wiki.archlinux.org/title/Plymouth

**Comment by Grosskopf** [comment]
oh, my impression was wrong, filesystems has no hook, so it does not quite matter where it goes during boot ^^

**Comment by root2185** [comment]
> there is still a known bug with them, when the password has been tried once it should show that but it does not due to one missing line in the hook

Will it be fixed?

>I think filesystems should be really late because I believe it tries to open files, and thus should happen after the files are unencrypted... with lvm2 i'm unsure where that goes, propably before unl0kr, because unl0kr needs to unlock a sub-partition inside an lvm partition...

I found the problem you need lvm2 AFTER unl0kr:
```
HOOKS=(base udev autodetect modconf kms keyboard keymap consolefont unl0kr lvm2 block filesystems resume fsck)
```
Also in this repo exmple it is before the osk keyboard. 
In my case with unl0kr I need it after.

But I can't use the touchscreen.
Do you need to enable modules in /etc/mkinitcpio.conf right?
I have a bunch already:
```
MODULES=(i915 hid_multitouch i2c_hid i2c_hid_acpi drm_buddy intel_gtt drm_display_helper cec ttm video wmi intel_hid)
```
How can I find the missing ones?

**Comment by ShapeShifter499** [comment]
@Grosskopf I'm deeply sorry I have not seen this before. I should add the GPL3 license. I don't really care if you use my code for your project. It's just a base to get a already established unlocking project, osk-sdl, compiling on and working on Arch Linux.

**Comment by Grosskopf** [comment]
> @Grosskopf I'm deeply sorry I have not seen this before. I should add the GPL3 license. I don't really care if you use my code for your project. It's just a base to get a already established unlocking project, osk-sdl, compiling on and working on Arch Linux.

Thank you :)

**Comment by Grosskopf** [comment]
> > there is still a known bug with them, when the password has been tried once it should show that but it does not due to one missing line in the hook
> 
> Will it be fixed?
> 

I am hoping I can get that to work, I somehow need to set the environment variable CRYPTTAB_TRIED to 1 after the first run of unl0kr, not sure how I do that in such a way that unl0kr notices, the usual way fails, but I'm still trying to get that to work

> > I think filesystems should be really late because I believe it tries to open files, and thus should happen after the files are unencrypted... with lvm2 i'm unsure where that goes, propably before unl0kr, because unl0kr needs to unlock a sub-partition inside an lvm partition...
> 
> I found the problem you need lvm2 AFTER unl0kr:
> 
> ```
> HOOKS=(base udev autodetect modconf kms keyboard keymap consolefont unl0kr lvm2 block filesystems resume fsck)
> ```
> 
> Also in this repo exmple it is before the osk keyboard. In my case with unl0kr I need it after.
> 
> But I can't use the touchscreen. Do you need to enable modules in /etc/mkinitcpio.conf right? I have a bunch already:
> 
> ```
> MODULES=(i915 hid_multitouch i2c_hid i2c_hid_acpi drm_buddy intel_gtt drm_display_helper cec ttm video wmi intel_hid)
> ```
> 
> How can I find the missing ones?

i just have these 3: `i915 crc32c-intel i2c-dev`

I have no idea how I would find missing ones, what helped for me was a `sleep 3` because unl0kr has an open bug about input devices having to initialize before unl0kr is run but I have no Idea how, have you tried setting this to a higher value?

**Comment by root2185** [comment]
```
                echo "A password is required to access the ${cryptname} volume"
                sleep 9 # await input devices initialisation
```
I tried with 9 seconds. 
Is it enough right?

I'll try with the `crc32c-intel` module.

**Comment by root2185** [comment]
I tried 9 seconds.
Is there a way to do some debug?

I also added the missing files from https://gitlab.com/postmarketOS/pmaports/-/blob/master/main/unl0kr/unl0kr.files.

**Comment by root2185** [comment]
```
#!/bin/ash
build() {
    local mod

    add_module "dm-crypt"
    add_module 'dm-integrity'
    if [[ $CRYPTO_MODULES ]]; then
        for mod in $CRYPTO_MODULES; do
            add_module "$mod"
        done
    else
        add_all_modules "/crypto/"
    fi

    add_binary 'cryptsetup'

    map add_udev_rule \
        '10-dm.rules' \
        '13-dm-disk.rules' \
        '95-dm-notify.rules' \
        '/usr/lib/initcpio/udev/11-dm-initramfs.rules'\

    # cryptsetup calls pthread_create(), which dlopen()s libgcc_s.so.1
    add_binary '/usr/lib/libgcc_s.so.1'

    add_binary /usr/bin/unl0kr
    add_file /etc/unl0kr.conf

    # add DRI drivers so we can have hw accel
    libdir=/usr/lib
    DRI_drivers="vmgfx_dri.so virtio_gpu_dri.so i965_drv_video.so crocus_dri.so iris_dri.so nouveau_dri.so r300_dri.so r600_dri.so radeonsi_dri.so zink_dri.so kms_swrast_dri.so"
    for so in $DRI_drivers; do
      if [ -f "$libdir/dri/$so" ]; then
          add_binary "$libdir/dri/$so"
      fi
    done

    add_binary "/usr/lib/libinput.so" 
    add_binary "/usr/lib/libinput.so.10"
    add_binary "/usr/lib/libinput.so.10.13.0" 
    add_binary "/usr/lib/libxkbcommon.so.0"
    #add_file "/usr/lib/udev/libinput-device-group"
    #add_file "/usr/lib/udev/libinput-fuzz-extract"
    #add_file "/usr/lib/udev/libinput-fuzz-to-zero"
    add_full_dir "/usr/lib/udev/rules.d"
    add_full_dir "/etc/udev/rules.d"
    add_full_dir "/usr/share/libinput"
    add_full_dir "/usr/share/X11/xkb"

    add_binary "$libdir/libGLESv2.so.2"
	add_binary "/usr/bin/udevadm"
	add_binary "/usr/bin/udevd"
	
    find -L "$libdir" -name "libGL*.so*" -o -name "libEGL*.so*" -o -name "libEGL_mesa.so*" -type f | while read -r so; do
       add_binary "$so"
    done

    [ -f /usr/share/glvnd/egl_vendor.d/50_mesa.json ] && add_file /usr/share/glvnd/egl_vendor.d/50_mesa.json

    ttf_font=$(grep "^keyboard-font\s" /etc/unl0kr.conf|cut -f3 -d' ')
    [ -f "$ttf_font" ] && add_file "$ttf_font"

    add_runscript
}

help() {
    cat <<HELPEOF
This hook loads unl0kr to decrypt the filesystem. Used on touchscreen devices like tablets and phones to provide an on screen keyboard in order to enter in a passphrase for decrypting encrypted systems when an keyboard is not present.
Users should specify the device to be unlocked using 'cryptdevice=device:dmname' on the kernel command line, where 'device' is the path to the raw device, and 'dmname' is the name given to the device after unlocking, and will be available as /dev/mapper/dmname.
HELPEOF
}
```

**Comment by Grosskopf** [comment]
> I tried 9 seconds. Is there a way to do some debug?
> 
> I also added the missing files from https://gitlab.com/postmarketOS/pmaports/-/blob/master/main/unl0kr/unl0kr.files.

So far I only did print debugging, these hook files in that folder are like shell scripts executed one after another at boot time, so you can echo stuff and uncomment stuff, the unl0kr command starts unl0kr, you could try executing libinput list devices or something like that and then have it sleep for some time so that you can read the results  or something like that. The problem I ran into was that I did not know how to do anything in the boot process.. maybe I should have tried starting a shell at that point... would be glad to hear more from your tests

**Comment by root2185** [comment]
I needed to add more file to the hook to use `libinput list-devices`.
I enabled the log so I can read easily the long output.

The touchscreen device `GXTP7386:00 27C6:011A` is not listed.
And also these are missing:
```
Power Button
Front Camera: Front Camera
Back Camera: Back Camera
GXTP7386:00 27C6:011A Stylus
GXTP7386:00 27C6:011A Keyboard
Intel HID events
Intel HID 5 button array
```
A missing module?
I now use `MODULES=(i2c-dev i915 crc32c_intel hid_multitouch i2c_hid i2c_hid_acpi)`.

**Comment by root2185** [comment]
Your files works perfectly I just needed the drivers.
Unfortunately I don't know what so I added them all: `add_all_modules "/drivers/"` in unl0kr-install.
You could add that line commented with a comment.
I need the 3 seconds sleep.

The right modules should be in `lsmod` output right?

```
udevadm info /dev/input/event5
P: /devices/pci0000:00/0000:00:17.0/i2c_designware.4/i2c-5/i2c-GXTP7386:00/0018:27C6:011A.0001/input/input10/event5
M: event5
R: 5
U: input
D: c 13:69
N: input/event5
L: 0
S: input/touchscreen
S: input/by-path/pci-0000:00:17.0-platform-i2c_designware.4-event
E: DEVPATH=/devices/pci0000:00/0000:00:17.0/i2c_designware.4/i2c-5/i2c-GXTP7386:00/0018:27C6:011A.0001/input/input10/event5
E: DEVNAME=/dev/input/event5
E: MAJOR=13
E: MINOR=69
E: SUBSYSTEM=input
E: USEC_INITIALIZED=23474462
E: ID_INPUT=1
E: ID_INPUT_TOUCHSCREEN=1
E: ID_INPUT_WIDTH_MM=259
E: ID_INPUT_HEIGHT_MM=142
E: ID_PATH=pci-0000:00:17.0-platform-i2c_designware.4
E: ID_PATH_TAG=pci-0000_00_17_0-platform-i2c_designware_4
E: LIBINPUT_DEVICE_GROUP=18/27c6/11a:i2c-GXTP7386:00
E: DEVLINKS=/dev/input/touchscreen /dev/input/by-path/pci-0000:00:17.0-platform-i2c_designware.4-event
```
https://github.com/torvalds/linux/blob/master/drivers/i2c/busses/i2c-designware-master.c.

I tried:
```
MODULES=(i915 crc32c_intel hid_multitouch i2c_hid i2c_hid_acpi i2c_i801 i2c_smbus nxp_nci_i2c intel_lpss)
```
I put all modules that have i2c, touch and lpss, from `lsmod`.
Plus yours. lpss is from `udevadm info -a /dev/input/event5`.
Thanks.

Note I use Artix and not Arch.
My device: CHUWI UBook.
